### ISSUE TITLE
Bulwark_mn3:# bulwark-cli getinfo error: couldn't connect to server

### ISSUE THREAD

**Issue by kmetax** [bulwark-crypto/Bulwark#152] opened 2018-12-23 16:49 UTC
*
Hi, 
my MN wallet ids not starting again with status missing can you help me?

root@Bulwark_mn3:~# bulwark-cli getinfo
error: couldn't connect to server
root@Bulwark_mn3:~# bulwark-cli mnsync status
error: couldn't connect to server
root@Bulwark_mn3:~# bulwark-cli masternode status
error: couldn't connect to server
root@Bulwark_mn3:~# systemctl status bulwarkd
● bulwarkd.service - Bulwarks's distributed currency daemon
   Loaded: loaded (/etc/systemd/system/bulwarkd.service; enabled; vendor preset:
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-12-23 16
  Process: 2031 ExecStop=/usr/local/bin/bulwark-cli -conf=/root/.bulwark/bulwark
  Process: 2015 ExecStart=/usr/local/bin/bulwarkd -conf=/root/.bulwark/bulwark.c
 Main PID: 2018 (code=exited, status=1/FAILURE)

Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Control process exited
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Unit entered failed st
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Failed with result 'ex
lines 1-10/10 (END)
● bulwarkd.service - Bulwarks's distributed currency daemon
   Loaded: loaded (/etc/systemd/system/bulwarkd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-12-23 16:38:57 UTC
  Process: 2031 ExecStop=/usr/local/bin/bulwark-cli -conf=/root/.bulwark/bulwark.conf -dat
  Process: 2015 ExecStart=/usr/local/bin/bulwarkd -conf=/root/.bulwark/bulwark.conf -datad
 Main PID: 2018 (code=exited, status=1/FAILURE)

Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Control process exited, code=exi
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Unit entered failed state.
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Failed with result 'exit-code'.

~
lines 1-10/10 (END)...skipping...
● bulwarkd.service - Bulwarks's distributed currency daemon
   Loaded: loaded (/etc/systemd/system/bulwarkd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2018-12-23 16:38:57 UTC
  Process: 2031 ExecStop=/usr/local/bin/bulwark-cli -conf=/root/.bulwark/bulwark.conf -dat
  Process: 2015 ExecStart=/usr/local/bin/bulwarkd -conf=/root/.bulwark/bulwark.conf -datad
 Main PID: 2018 (code=exited, status=1/FAILURE)

Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Control process exited, code=exi
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Unit entered failed state.
Dec 23 16:38:57 Bulwark_mn3 systemd[1]: bulwarkd.service: Failed with result 'exit-code'.

**Comment by VoxTerra77** [comment] 2018-12-26 22:40
`Could not connect to server` indicates that your daemon crashed, the simple fix is to refresh your node using the refresh script found [here](https://kb.bulwarkcrypto.com/Guides/Refresh-Guide/). 

As for the cause of the crash, we're still investigating the possible issues that are causing nodes to crash and will update everyone when we have more information about it. The refresh script should get you back up and running in the meantime.

**Comment by dustinengle** [comment] 2018-12-27 22:49
Duplicate of #146, please reference there for more information.

**Closed by dustinengle** 2018-12-27 22:49 UTC
Labels: investigating, masternode
