### ISSUE TITLE
MN crash

### ISSUE THREAD

**Issue by VoxTerra77** [bulwark-crypto/Bulwark#150] opened 2018-12-20 04:49 UTC
**Describe the bug**

*reporting for a user with completed information*
My MN goes down for 5 times continusly

here is teh debug log link: https://transfer.sh/Rat9P/debug.logroot@ubuntu-s-1vcpu-1gb-nyc1-01:~#

**To Reproduce**
1. Set up node with standard VPS script
2. wait 3-4 days
3. Crash

**Expected behavior**
Stability

**VPS (please complete the following information):**
 - Provider: DigitalOcean
 - OS: Ubuntu
 - Version:  ?
 - Specs: 1gb RAM, CPU ?

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dustinengle** [comment] 2018-12-27 22:52
Duplicate of #146, please reference there for more information.

**Closed by dustinengle** 2018-12-27 22:52 UTC
Labels: investigating, masternode
